name: SCSCP
version: 2.2.3
date: 2017-09-24
description: |
    Symbolic Computation Software Composability Protocol in GAP

authors:
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/
    - name: Steve Linton
      url: http://www.cs.st-and.ac.uk/~sal/

maintainers:
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/
    - name: Steve Linton
      url: http://www.cs.st-and.ac.uk/~sal/

GAP: ">=4.8.2"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "openmath"
      version: ">= 11.4.1"
      url: "https://gap-packages.github.io/openmath"
    - name: "IO"
      version: ">= 4.4"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/scscp
readme: README.md
packageinfo: https://gap-packages.github.io/scscp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/scscp/releases/download/v2.2.3/SCSCP-2.2.3.tar.gz

abstract: |
    This package implements the <a href="http://www.symbolic-computing.org/scscp">Symbolic Computation Software Composability Protocol</a> for the GAP system.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
